### ISSUE TITLE
try open status file

### ISSUE THREAD

**Issue by pgdr** [equinor/libres#232]
This happened when running Everest:

```
seba: Simulation "Batch1_Grad1_Func1" started.
Traceback (most recent call last):
  File "/project/res/komodo/unstable/root/bin/job_dispatch.py", line 409, in <module>
    main( sys.argv )
  File "/project/res/komodo/unstable/root/bin/job_dispatch.py", line 365, in main
    job_manager.completeStatus(exit_status, error_msg, job=job)
  File "/project/res/komodo/unstable/root/lib/python2.7/site-packages/res/job_queue/job_manager.py", line 285, in completeStatus
    with open(self.STATUS_file, "a") as f:
IOError: [Errno 2] No such file or directory: 'STATUS'
```

Should we check if the file exists before opening it, and if not, try to wait a while or return an error message?

**Comment by pgdr** [comment]
Cosmic rays
