### ISSUE TITLE
ERT plotting crashes when selecting plot from the ERT menu. 

### ISSUE THREAD

**Issue by geirev** [equinor/libres#582]
gert gui poly.ert
ERT plotting crashes with the following message when selecting Plot from the ERT menu. 

Traceback (most recent call last):                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/ert_gui/tools/plot/plot_tool.py", line 11, in trigger                             
    plot_window = PlotWindow(self.parent())                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/ert_gui/tools/plot/plot_window.py", line 44, in __init__                          
    self._plot_customizer = PlotCustomizer(self, self._ert.plotConfig())                                                         
AttributeError: 'EnKFMain' object has no attribute 'plotConfig'

**Comment by xjules** [comment]
The PR that fixes it is in the process https://github.com/equinor/ert/pull/376
Travis's broken though.

**Comment by markusdregi** [comment]
As @xjules said, this is a known effect of working on the configuration setup in _libres_. However, if you use _libres_ version denoted by https://github.com/equinor/ert/blob/master/.libres_version, that should always give you a version of _libres_ compatible with _ERT_ master.

**Comment by markusdregi** [comment]
Thank you for reporting :+1:
