### ISSUE TITLE
Possible bug in workflow runner

### ISSUE THREAD

**Issue by ManInFez** [equinor/libres#913]
Multiple users report following error when running workflow
```
Traceback (most recent call last):
  File "/prog/res/komodo/2020.02.01-py27/root/lib/python2.7/site-packages/ert_gui/tools/workflows/run_workflow_widget.py", line 141, in workflowFinishedWithFail
    error = self._workflow_runner.workflowError()
  File "/prog/res/komodo/2020.02.01-py27/root/lib/python2.7/site-packages/res/job_queue/workflow_runner.py", line 78, in workflowError
    for error_line in error:
TypeError: 'NoneType' object is not iterable
```

Conversation found here: https://equinor.slack.com/archives/CDPJULWR4/p1582812077085900

**Comment by jondequinor** [comment]
POI from the conversation:

- seems to be not particular to anything other than `MAPS_` prefixed workflows
- error is thrown immediately after pressing play on the workflow

**Comment by jondequinor** [comment]
I've found this to be a classic _TOCTOU_ here: https://github.com/equinor/ert/blob/9e838747f8c56683cf83ee21f4ec7f2640e21efb/ert_gui/tools/workflows/run_workflow_widget.py#L111
