### ISSUE TITLE
.PRT files from ECLIPSE get corrupted (?); Python 3 assumes they're UTF-8

### ISSUE THREAD

**Issue by pinkwah** [equinor/libres#926]
On Slack: https://equinor.slack.com/archives/CDPJULWR4/p1585918748131500

> Hi,
> I have been trying to run a series of 7 DST simulation files. The job modifies the reservoir model DATA file and generates the DST DATA files. Simulating them in series, I get the following error on the last one:
```
<error>
  <time>14:39:49</time>
  <job>ECLIPSE100</job>
  <reason>Process exited with status code 1</reason>
  <stderr>
Traceback (most recent call last):
  File "/prog/res/komodo/2020.03.rc2-py36/root/share/ert/forward-models/res/script/ecl100", line 6, in <module>
    run(config, [arg for arg in sys.argv[1:] if len(arg) > 0])
  File "/prog/res/komodo/2020.03.rc2-py36/root/lib/python3.6/site-packages/res/fm/ecl/script.py", line 22, in run
    run.runEclipse()
  File "/prog/res/komodo/2020.03.rc2-py36/root/lib/python3.6/site-packages/res/fm/ecl/ecl_run.py", line 217, in runEclipse
    self.assertECLEND( )
  File "/prog/res/komodo/2020.03.rc2-py36/root/lib/python3.6/site-packages/res/fm/ecl/ecl_run.py", line 259, in assertECLEND
    error_list = self.parseErrors( )
  File "/prog/res/komodo/2020.03.rc2-py36/root/lib/python3.6/site-packages/res/fm/ecl/ecl_run.py", line 295, in parseErrors
    content = f.read()
  File "/prog/res/komodo/2020.03.rc2-py36/root/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 157380: invalid start byte
</stderr>
  <stderr_file>/scratch/johan_sverdrup/hojm/2020a_b007p0p0_4_test1_dst/realization-0/pred/ECLIPSE100.stderr.11</stderr_file>
</error>
```
> I have seen the error since started using Py3 in other scripts and fixed it with encoding='cp1252' in open() function. Here I don't have an access to the script and I am not sure my solution is the correct one either. Any suggestion?

**Comment by sondreso** [comment]
From slack:

> [Someone] discovered an Eclipse error in lgr which was reported in Print file. By fixing the error the problem goes away. It seems that the ert message was irrelevant to the error.

**Comment by pinkwah** [comment]
Is failure to parse .PRT files as utf8 reason to crash? We can perhaps assume that they're ASCII and replace unknown characters with ?.

**Comment by sondreso** [comment]
Yes, that would be a solution, but I don't think we should prioritize such safeguards at the moment. We are able to parse correctly formatted files, which I think covers 99.9 % of the use cases.
