### ISSUE TITLE
Issue related to job monitoring for RSH, LOCAL ,and TORQUE queues

### ISSUE THREAD

**Issue by eivindsm** [equinor/libres#958]
I have observed an recurrent  issue with the job monitoring during ensemble_experiments in ERT. At some point during runs ERT looses track of one or more processes. The logger then accounts for a total amount lower than the total submitted number of jobs. Same issue observed with ques LOCAL, RSH and TORQUE
     ■ Finished        15/80
    ■ Failed           0/80
    ■ Running         58/80
    ■ Unknown          0/80
    ■ Pending          0/80
    ■ Waiting          0/80
qstat: End of File 7999.zwe-lcUm
** Warning: failed to get job status for job:7999 from file:/tmp/enkf-qstat-24056-715175
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/prog/res/komodo/2020.05.01-py27/root/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/prog/res/komodo/2020.05.01-py27/root/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/prog/res/komodo/2020.05.01-py27/root/lib/python2.7/site-packages/res/job_queue/job_queue_node.py", line 145, in _job_monitor
    raise AssertionError("Unexpected job status type after running job: {}".format(self.status))
AssertionError: Unexpected job status type after running job: 4096

**Comment by markusdregi** [comment]
This issue has not been reproduced in a long time. Closing.
